### ISSUE TITLE
Cannot read property 'enabled' of undefined

### ISSUE THREAD

**Issue by boris-petrov** [tim-evans/ember-page-title#115]
After upgrading to `4.0.0`:

```
Cannot read property 'enabled' of undefined
TypeError: Cannot read property 'enabled' of undefined
    at Class.findHost [as _findHost] (/home/boris/ember-app/node_modules/ember-engines/lib/engine-addon.js:71:29)
    at Class.options.init (/home/boris/ember-app/node_modules/ember-engines/lib/engine-addon.js:534:40)
    at Class.superWrapper [as init] (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at new CoreObject (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:9:15)
    at new Class (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:21:5)
    at new Class (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:21:5)
    at graph.each (/home/boris/ember-app/node_modules/ember-cli/lib/models/addons-factory.js:58:19)
    at Vertices.each (/home/boris/ember-app/node_modules/dag-map/dag-map.umd.js:197:13)
    at Vertices.walk (/home/boris/ember-app/node_modules/dag-map/dag-map.umd.js:125:14)
    at DAG.each (/home/boris/ember-app/node_modules/dag-map/dag-map.umd.js:68:24)
    at AddonsFactory.initializeAddons (/home/boris/ember-app/node_modules/ember-cli/lib/models/addons-factory.js:45:11)
    at Class.initializeAddons (/home/boris/ember-app/node_modules/ember-cli/lib/models/addon.js:364:38)
    at setupRegistryForEachAddon (/home/boris/ember-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/home/boris/ember-app/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
    at Class.init (/home/boris/ember-app/node_modules/ember-cli/lib/models/addon.js:227:7)
    at Class.superWrapper [as init] (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at new CoreObject (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:9:15)
    at new Class (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:21:5)
    at new Class (/home/boris/ember-app/node_modules/ember-cli/node_modules/core-object/core-object.js:21:5)
    at graph.each (/home/boris/ember-app/node_modules/ember-cli/lib/models/addons-factory.js:58:19)
    at Vertices.each (/home/boris/ember-app/node_modules/dag-map/dag-map.umd.js:197:13)
    at Vertices.walk (/home/boris/ember-app/node_modules/dag-map/dag-map.umd.js:125:14)
    at DAG.each (/home/boris/ember-app/node_modules/dag-map/dag-map.umd.js:68:24)
    at AddonsFactory.initializeAddons (/home/boris/ember-app/node_modules/ember-cli/lib/models/addons-factory.js:45:11)
    at Project.initializeAddons (/home/boris/ember-app/node_modules/ember-cli/lib/models/project.js:442:38)
    at Project.eachAddonCommand (/home/boris/ember-app/node_modules/ember-cli/lib/models/project.js:504:12)
    at module.exports (/home/boris/ember-app/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)
    at RSVP.hash.then.environment (/home/boris/ember-app/node_modules/ember-cli/lib/cli/cli.js:97:28)
    at tryCatch (/home/boris/ember-app/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/boris/ember-app/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/boris/ember-app/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/boris/ember-app/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

An error occurred in the constructor for addon-docs at /home/boris/ember-app/node_modules/addon-docs
An error occurred in the constructor for ember-page-title at /home/boris/ember-app/node_modules/ember-page-title
```

P.S. This `addon-docs` package seems to add a HUGE amount of dependencies. Can't you go without it or mark it as a test-dependency or something?

**Comment by urbany** [comment]
I'm getting the same error after upgrading to 4.0.0 from 3.2.2
Using latest stable version of ember-cli.

**Comment by tim-evans** [comment]
Grr. Optional dependencies don't seem to work here. Do you have any ideas for how to fix this?

**Comment by CvX** [comment]
We could just drop addon-docs (as it doesn't seem to provide much value in this package at the moment) or we could move those two dependencies to devDeps. Correct?

**Comment by tim-evans** [comment]
Addon-docs is used for the documentation site

**Comment by tim-evans** [comment]
I think devDependencies may work

**Comment by tim-evans** [comment]
Apologies for this; I removed the dependencies. I think the docs work best as-is.

**Comment by tim-evans** [comment]
Try using 4.0.1
