### ISSUE TITLE
Merge error: file app.scss exists

### ISSUE THREAD

**Issue by buschtoens** [tim-evans/ember-page-title#21]
```
[jan@arch exam-schedule]$ ember v
version: 1.13.8
node: 3.2.0
npm: 2.13.4
os: linux x64
[jan@arch exam-schedule]$ ember s --host ::
version: 1.13.8
Livereload server on http://:::49152
Serving on http://:::4200/
Merge error: file app.scss exists in /home/jan/ember/exam-schedule/tmp/broccoli_merge_trees-input_base_path-pudC0ESO.tmp/23 and /home/jan/ember/exam-schedule/tmp/broccoli_merge_trees-input_base_path-pudC0ESO.tmp/25
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
Error: Merge error: file app.scss exists in /home/jan/ember/exam-schedule/tmp/broccoli_merge_trees-input_base_path-pudC0ESO.tmp/23 and /home/jan/ember/exam-schedule/tmp/broccoli_merge_trees-input_base_path-pudC0ESO.tmp/25
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
    at mergeRelativePath (/home/jan/ember/exam-schedule/node_modules/ember-component-css/node_modules/broccoli-merge-trees/index.js:118:19)
    at BroccoliMergeTrees.build (/home/jan/ember/exam-schedule/node_modules/ember-component-css/node_modules/broccoli-merge-trees/index.js:36:3)
    at /home/jan/ember/exam-schedule/node_modules/ember-component-css/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/jan/ember/exam-schedule/node_modules/ember-component-css/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jan/ember/exam-schedule/node_modules/ember-component-css/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/jan/ember/exam-schedule/node_modules/ember-component-css/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/jan/ember/exam-schedule/node_modules/ember-component-css/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
[jan@arch exam-schedule]$ cat package.json
{
  "name": "exam-schedule",
  "version": "0.0.0",
  "description": "Small description for exam-schedule goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-autoprefixer": "0.5.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-emblem": "0.3.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-mirage": "0.1.8",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-release": "0.2.3",
    "ember-cli-sass": "4.2.0",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-simple-auth-token": "0.7.3",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-component-css": "0.1.6",
    "ember-data": "1.13.8",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-noscript": "2.0.0",
    "ember-page-title": "2.0.6",
    "ember-suave": "1.0.0",
    "liquid-fire": "0.21.2"
  }
}
```
Installing `ember-page-title` triggers the above error on build. I use a (non-empty) `styles/app.sass` file, if that matters.

Could this possibly be an incompatibility with another addon that [uses the same hack](https://github.com/tim-evans/ember-page-title/blob/master/app/styles/app.scss)?

As a temporary fix, this seems to work:

```bash
$ rm node_modules/ember-page-title/app/styles/app.scss
```

On a related note: What is the reason for this hack - what does this addon have to do with styles?

**Comment by tim-evans** [comment]
This addon builds documentation using the tests/dummy directory. There's a bug which prevents this from working without that file. It seems that this totally breaks apps that use this. I'll publish a new release without this file as a stop-gap measure.

**Comment by tim-evans** [comment]
See https://github.com/ember-cli/ember-cli/pull/3344 for more info on this.

**Comment by tim-evans** [comment]
@buschtoens could you try 2.0.7? I've fixed it by using a prepublish / postpublish script in package.json to prevent this from happening.

**Comment by buschtoens** [comment]
Awesome! Works like a charm. Thanks a lot. :)
