### ISSUE TITLE
Doesn't work with ember-cli-fastboot@1.0.0-rc.1

### ISSUE THREAD

**Issue by buschtoens** [tim-evans/ember-page-title#69]
```json
$ ember v
ember-cli: 2.13.2
node: 8.0.0-pre
os: linux x64

$ cat package.json | jq '.devDependencies'
{
  "broccoli-asset-rev": "^2.4.5",
  "ember-ajax": "^3.0.0",
  "ember-cli": "2.13.2",
  "ember-cli-app-version": "^3.0.0",
  "ember-cli-babel": "^6.0.0",
  "ember-cli-dependency-checker": "^1.3.0",
  "ember-cli-eslint": "^3.0.0",
  "ember-cli-fastboot": "1.0.0-rc.1",
  "ember-cli-htmlbars": "^1.1.1",
  "ember-cli-htmlbars-inline-precompile": "^0.4.0",
  "ember-cli-inject-live-reload": "^1.4.1",
  "ember-cli-polyfill-io": "^1.2.2",
  "ember-cli-qunit": "^4.0.0",
  "ember-cli-shims": "^1.1.0",
  "ember-cli-sri": "^2.1.0",
  "ember-cli-uglify": "^1.2.0",
  "ember-data": "^2.13.0",
  "ember-export-application-global": "^2.0.0",
  "ember-intl": "^2.27.0",
  "ember-load-initializers": "^1.0.0",
  "ember-page-title": "^3.1.6",
  "ember-resolver": "^4.0.0",
  "ember-source": "~2.13.0",
  "loader.js": "^4.2.3"
}

$ ember serve
FastBoot build no longer supports /home/jan/github/buschtoens/node_modules/ember-page-title/app/(instance-)?initializers/browser structure. Please refer to www.ember-fastboot.com for a migration path.
Error: FastBoot build no longer supports /home/jan/github/buschtoens/node_modules/ember-page-title/app/(instance-)?initializers/browser structure. Please refer to www.ember-fastboot.com for a migration path.
    at _checkBrowserInitializers (/home/jan/github/buschtoens/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:39:11)
    at project.addons.forEach (/home/jan/github/buschtoens/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:97:5)
    at Array.forEach (native)
    at _migrateAddonInitializers (/home/jan/github/buschtoens/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:94:18)
    at migrateInitializers (/home/jan/github/buschtoens/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:121:3)
    at Class.included (/home/jan/github/buschtoens/node_modules/ember-cli-fastboot/index.js:58:5)
    at EmberApp.<anonymous> (/home/jan/github/buschtoens/node_modules/ember-cli/lib/broccoli/ember-app.js:517:17)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/home/jan/github/buschtoens/node_modules/ember-cli/lib/broccoli/ember-app.js:512:47)
    at new EmberApp (/home/jan/github/buschtoens/node_modules/ember-cli/lib/broccoli/ember-app.js:142:10)
```

Just so you know :sweat_smile:

**Comment by buschtoens** [comment]
Relevant code throwing the exception: [`migrate-initializers.js`](https://github.com/ember-fastboot/ember-cli-fastboot/blame/1ba0854b4580af49248b09ddc17df36b22977f0a/lib/build-utilities/migrate-initializers.js#L37-L38)

**Comment by buschtoens** [comment]
https://github.com/ember-fastboot/ember-cli-fastboot/issues/387

**Comment by kratiahuja** [comment]
There is guide/cheat sheet in that issue that you use to make your addon backward compatible.

**Comment by buschtoens** [comment]
Specifically: (Addon contains browser based initializers as app/(instance-)?initializers/browser/*js)[https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c#addon-contains-browser-based-initializers-as-appinstance-initializersbrowserjs]

Maybe I'll get around to submit a PR in a few hours. :slightly_smiling_face:

**Comment by tim-evans** [comment]
@buschtoens I would love that!
